service: citizenplane-service

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  apiKeys:
    - service-key
plugins:
  - serverless-domain-manager
custom:
  customDomain:
    domainName: service.citizenplane.com
    certificateName: '*.citizenplane.com'
functions:
  api:
    handler: index.handler
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true